name: Deploy page

on:
  push:
   branches: ['master']

jobs:
  build_master:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.head_ref }}
       token: ${{ github.token }}
    - uses: actions/setup-node@master
      with:
       node-version: 12
#     - uses: oleksiyrudenko/gha-git-credentials@v2.1
#       with:
#         global: true
#         name: 'Wassim Ben Jdida'
#         email: 'wassimbenjdida@gmail.com'
#         actor: ${{ github.actor }}
#         token: ${{ github.token }}
    - run: npm ci
    - run: npm run deploy
